### ISSUE TITLE
SerializableEntityStateTypeDrawer could be improved

### ISSUE THREAD

**Issue by TheTimeSweeper** [risk-of-thunder/RoR2EditorKit#18]
The inspector and search function currently only show the name rather than the full name. This is a bit inconvenient in the very common case of setting CharacterDeathBehavior to EntityStates.Commando.DeathState. you can't search the namespace, you can't search commando, and if you search just DeathState you get many duplicates, impossible to tell which is the right one.

suggestions:
- display and be able to search the full type name in the search window
- attempt to display the full type name in the property drawer as well, graying out the namespace before the type, and truncating the beginning with ...

**Comment by Nebby1999** [comment]
Not exactly mentioned, but this is already a feature. You can go into the RoR2EditorKit's preference settings and change it so that the item name is the type's full name, which includes its namespace.

See [SerializableSystemType](https://github.com/risk-of-thunder/RoR2EditorKit/blob/0a5d4c7644e7ebcfc977a6332e9190bb4d263b16/Editor/RoR2/PropertyDrawers/SerializableSystemTypeDrawer.cs#L23-L24) and [InheritingTypeSelectDropdown](https://github.com/risk-of-thunder/RoR2EditorKit/blob/0a5d4c7644e7ebcfc977a6332e9190bb4d263b16/Editor/Core/Dropdowns/InheritingTypeSelectDropdown.cs#L49).

Since this is a preference setting, it'll be stored across all your projects that use ror2editorkit
